name: Maven Build

on:
  push:
    branches:
      - main  # Trigger the workflow for pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for your job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

